name: gitleaks

on:
  pull_request:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # 添加下面这一行，确保准确拉取触发事件时的目标 commit
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Scan for secrets
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_CONFIG: .gitleaks.toml
          GITLEAKS_ENABLE_COMMENTS: "false"
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
